export enum ASSET_TYPE {
  LAND = 'LAND',
  BUILDING = 'BUILDING',
  MOTOR_VEHICLE = 'MOTOR_VEHICLE',
}

export enum DealStage {
  OFFER = 'OFFER',
  NEGOTIATION = 'NEGOTIATION',
  CONTRACT_DRAFTING = 'CONTRACT_DRAFTING',
  CONTRACT_SIGNING = 'CONTRACT_SIGNING',
  PAYMENT = 'PAYMENT',
  COMPLETED = 'COMPLETED',
}
