export enum UserType {
  BUYER = 'BUYER',
  OWNER = 'OWNER',
}

export enum STORAGE_INFO {
  TOKEN = 'TOKEN',
  USER_ID = 'USER_ID',
  LANGUAGE = 'LANGUAGE',
  GTFS = 'GTFS',
  IS_INITIAL_LANGUAGE_SET = 'IS_INITIAL_LANGUAGE_SET',
  IS_REGISTERED = 'IS_REGISTERED',
  STAFF_SETTINGS = 'STAFF_SETTINGS',
  LOGIN_OPTIONS = 'LOGIN_OPTIONS',
  LOGIN_CREDENTIALS = 'LOGIN_CREDENTIALS',
}

export enum PaymentType {
  LAMPSUM = 'LAMPSUM',
  INSTALLMENT = 'INSTALLMENT',
}
